---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test2
  annotations:
    github.com/project-slug: alokmaurya1/test2
    backstage.io/techdocs-ref: value  
spec:
  type: other
  lifecycle: development
  owner: alokmaurya1
  user: alokmaurya1
  tags: dev
