---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test2
  annotations:
    github.com/project-slug: alokmaurya1/test2
    backstage.io/techdocs-ref: alokmaurya1/test2  
spec:
  type: other
  lifecycle: unknown
  owner: alokmaurya1
