---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test2
  annotations:
    github.com/project-slug: alokmaurya1/test2
    backstage.io/techdocs-ref: 'github:https://github.com/backstage/backstage/blob/master/plugins/techdocs-backend/examples/documented-component'
spec:
  type: other
  lifecycle: development
  owner: alok.maurya@citiustech.com
