pipeline
{
    agent {
        label 'master'
    }
    stages
    {
       stage('hola')
        {
            steps
            {
                sh '''
                echo "hola jenkins"
                '''
            }
        }
     }
}     
